/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    ACCOUNT_0: process.env.ACCOUNT_0,
    ACCOUNT_1: process.env.ACCOUNT_1,
    ACCOUNT_2: process.env.ACCOUNT_2,
    ACCOUNT_3: process.env.ACCOUNT_3,
    ACCOUNT_4: process.env.ACCOUNT_4,
    ACCOUNT_5: process.env.ACCOUNT_5,
    ACCOUNT_6: process.env.ACCOUNT_6,
    ACCOUNT_7: process.env.ACCOUNT_7,
    ACCOUNT_8: process.env.ACCOUNT_8,
    ACCOUNT_9: process.env.ACCOUNT_9,
    ACCOUNT_10: process.env.ACCOUNT_10,
    ACCOUNT_11: process.env.ACCOUNT_11,
    ACCOUNT_12: process.env.ACCOUNT_12,
    ACCOUNT_13: process.env.ACCOUNT_13,
    ACCOUNT_14: process.env.ACCOUNT_14,
    ACCOUNT_15: process.env.ACCOUNT_15,
    ACCOUNT_16: process.env.ACCOUNT_16,
    ACCOUNT_17: process.env.ACCOUNT_17,
    ACCOUNT_18: process.env.ACCOUNT_18,
    ACCOUNT_19: process.env.ACCOUNT_19,
    SIGNER_KEY: process.env.SIGNER_KEY,
    TOKENY: process.env.TOKENY,
    CLAIM_ISSUER: process.env.CLAIM_ISSUER,
    USER1: process.env.USER1,
    USER2: process.env.USER2,
    AGENT: process.env.AGENT,
    CLAIM_TOPICS_REGISTRY: process.env.CLAIM_TOPICS_REGISTRY,
    TRUSTED_ISSUERS_REGISTRY: process.env.TRUSTED_ISSUERS_REGISTRY,
    IDENTITY_REGISTRY_STORAGE: process.env.IDENTITY_REGISTRY_STORAGE,
    DEFAULT_COMPLIANCE: process.env.DEFAULT_COMPLIANCE,
    IDENTITY_REGISTRY: process.env.IDENTITY_REGISTRY,
    TOKEN_ONCHAIN_ID: process.env.TOKEN_ONCHAIN_ID,
    IMPLEMENTATION_AUTHORITY: process.env.IMPLEMENTATION_AUTHORITY,
    TOKEN_PROXY: process.env.TOKEN_PROXY,
    TOKEN: process.env.TOKEN,
    CLAIM_ISSUER: process.env.CLAIM_ISSUER,
    USER1_IDENTITY: process.env.USER1_IDENTITY,
    USER2_IDENTITY: process.env.USER2_IDENTITY,

  },
};

module.exports = nextConfig;
